### ISSUE TITLE
Commas affect carret position in NumericInput

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/react-polymorph#112]
As you can see in the below gif, whenever a comma is added to the input, the carret moves automatically to the left and when a comma is removed, the carret removes to the right.

This bug was not present in React-Polymorph 8.0.0

If I had to guess, it was probably introduced by [this commit](https://github.com/input-output-hk/react-polymorph/commit/62f2fec1b7f1695d5bc8ac4b6f5cc1bd6e9a674a#diff-36cd38f49b9afa08222c0dc9ebfe35eb)
![numeric_input_Bug](https://user-images.githubusercontent.com/2608559/59145434-de9d1800-8a1e-11e9-9286-40bfe11ea815.gif)

**Comment by DominikGuzei** [comment]
Hey @SebastienGllmt, thanks for the feedback - im already working on a complete re-write of the numeric input component and will take this into account!
