### ISSUE TITLE
Tooltip component

### ISSUE THREAD

**Issue by DominikGuzei** [input-output-hk/react-polymorph#26]
My initial idea here: it would be awesome if we could take the skin/styles from the "background bubble" we use for the select component and extract it into a separate (reusable) `Bubble` (feel free to suggest a better name) component which can be re-used by `Select`, `Tooltip` (and potentially `Dropdown` later on).

In the end we need a simple component that can be used for something like this:
<img width="904" alt="screenshot 2017-12-05 um 15 38 58" src="https://user-images.githubusercontent.com/172414/33612896-5638779a-d9d3-11e7-9c93-a8236fc93e47.png">

**Comment by bendyorke** [comment]
I'll get started on this now.  Is there any way you'd like it to be marked as 'in progress'?

**Comment by DominikGuzei** [comment]
Great @bendyorke! i set the `WIP` label for you, i think that's good enough for now 😉 
If you have any questions or need help with the coding, just drop me a line!

**Comment by DominikGuzei** [comment]
The CSS specs for the tooltip bubble are:
```
background-color: rgba(94, 96, 102, 0.9);
border-radius: 4px;
box-shadow: 0 1.5px 5px 0 rgba(0, 0, 0, 0.18);
padding: 6px 12px;
```

**Comment by DominikGuzei** [comment]
The tooltip component has been introduced in #32
