### ISSUE TITLE
Better prop naming for NumericInput

### ISSUE THREAD

**Issue by clemenshelm** [input-output-hk/react-polymorph#51]
I find the `maxBeforeDot` and `maxAfterDot` props on `NumericInput` a bit confusing. It starts with the word "dot" having no meaning in English related to numbers (except for the "dot product" in matrices). What we're referring to here is the "point" or "decimal point", so a first helpful step would be to name it appropriately.

I'd also suggest to assimilate the props to the `input` attributes HTML already offers us. We could use `maxLength` to define the maximum number of characters.

For the number of decimal places we could use the `step` attribute of number inputs, but that feels a bit hackish. For example, if we wanted to allow 2 (or less) decimal places, we'd have to write `step="0.01"`. Alternatively, we could add a prop `maxDecimal="2"` which I'd consider more intuitive.

**Comment by DominikGuzei** [comment]
Thanks @clemenshelm, great feedback!
@tomothespian @nikolaglumac please take a look!

**Comment by tomothespian** [comment]
Nice, thanks @clemenshelm 👍

**Comment by nikolaglumac** [comment]
@clemenshelm let's see if I got this straight - you would like to do the following:
- introduce new prop `maxLength` (which is a sum of all digits both integer and decimal part)
- rename `maxAfterDot` to `maxDecimal` 
- kick out `maxBeforeDot` and calculate it from: `maxLength - maxDecimal`

If that is the case then I must say I would rather just rename:
- rename `maxBeforeDot` to `maxInteger` 
- rename `maxAfterDot` to `maxDecimal` (same as you would) 

What do you think?

**Comment by clemenshelm** [comment]
Yes, exactly. I think `maxLength` should be defined anyway. And since providing `maxDecimal` implies `maxBeforeDot`, it doesn't make sense to keep `maxBeforeDot`.

**Comment by nikolaglumac** [comment]
@clemenshelm the only problem is that in numeric input we also have thousands `,` and decimal separators `.` - presumably they should not be counted into the `maxLength` quota 😂

**Comment by clemenshelm** [comment]
@nikolaglumac from my understanding they should be counted because `maxLength` refers to the maximum number of characters in the input element. The current `maxBeforeDot` also includes the thousands separator. Otherwise you would specify `maxValue` which also exists 😄 

But yes, the definition above was off by one: `maxBeforeDot === maxLength - maxDecimal - 1` (because comma)

**Comment by clemenshelm** [comment]
Which made me notice another thing: `maxValue` and `minValue` could be renamed to `max` and `min` to provide the same interface as the `<input type="number" />` HTML element 😉 

https://www.w3schools.com/jsref/dom_obj_number.asp
