### ISSUE TITLE
Default skin prop

### ISSUE THREAD

**Issue by clemenshelm** [input-output-hk/react-polymorph#52]
Have you already thought about defining a default value for the `skin` prop?

**Advantage**: Less code as long as you stick to the default skins.
**Disadvantage**: The default skin will always be bundled unless we manage to do some magic with `import()`.

**Comment by MarcusHurney** [comment]
@clemenshelm 
I've also considered this many times will working on the library and agree with you here on both the advantage and disadvantage. I haven't discussed it with anyone, but I think it's worth exploring.

**Comment by DominikGuzei** [comment]
Latest version of react-polymorph uses default skins in all components.
