### ISSUE TITLE
Troubles using simple Input/InputSkin components with newest webpack 4 loader configuration

### ISSUE THREAD

**Issue by chisNaN** [input-output-hk/react-polymorph#59]
Hello to maintainers of react-polymorph code.
First, thanks to share this react framework to the community.
I face a (probably obvious) problem using the simplest components (as described in the official readme).

1) to be able to compile (react-polymorph) successfully in my project i had previously to do the following

`yarn add node-sass react-css-themr lodash classnames -D`

2) adapt my webpack 4 config with the following loader sections (maybe my problem comes from there?)

(note the postfix "-loader")

```
{
        test: /\.scss$/,
        use: [
          'style-loader?sourceMap',
          'css-loader?sourceMap&modules&localIdentName=[name]_[local]&importLoaders=1',
          'sass-loader?sourceMap',
        ],
      }
```

3) my test project is a simple [react-router starter basic example](https://reacttraining.com/react-router/web/example/basic)

where i:

- separated all components in different files
- added the following code to the `About.jsx` component

```js
import React from 'react';
// import EB from './ErrorBoundary';
import Input from 'react-polymorph/lib/components/Input';
import InputSkin from 'react-polymorph/lib/skins/simple/InputSkin';

export default () => (
  <div>
    <h2>About</h2>
    <Input skin={InputSkin} />
  </div>
);
```

But I end up with the following errors (i have attached a screenshot) when i visit the About section:

```
warning.js:33 Warning: Failed prop type: Invalid prop `skin` of type `function` supplied to `Input`, expected a single ReactElement.
```
and

```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

Actually I already saw that error and went to google but could not manage to debug this time(((.
Any suggestions or help would be welcome.

Thanks for reading me

(i attach my webpack config, package.json and screenshot errors
![capture d ecran 2018-05-10 a 12 17 50](https://user-images.githubusercontent.com/2439389/39865372-f1723d7e-544c-11e8-9326-9c567cf55ed5.png)
[package.txt](https://github.com/input-output-hk/react-polymorph/files/1991252/package.txt)
[webpack.config.txt](https://github.com/input-output-hk/react-polymorph/files/1991255/webpack.config.txt)

)

**Comment by MarcusHurney** [comment]
@chisNaN 
Thanks for your interest in react-polymorph! If you are still interested in using the library for your project I would recommend using the develop branch. The library has undergone many changes over the past few months and the next will release will introduce a new API in the master branch. I recommend taking a look at the stories available for each component. After cloning the repo and checking out the develop branch, run **npm install** and then **npm run storybook**. Take a look at the stories directory for code examples.

**Comment by chisNaN** [comment]
Thanks sir for the reactivity and indications

**Comment by DominikGuzei** [comment]
@chisNaN as the error message indicates you need to install Xcode (the whole app, not just the command line tools) 😉

**Comment by MarcusHurney** [comment]
@chisNaN 
After you install Xcode: to run the component stories via storybook, please either pull the latest changes from the master branch and reinstall dependencies using **yarn**, or if you're using react-polymorph as a dependency in another project, please use version 0.7.0 as this is the latest release that's been made available since we last spoke.

**Comment by chisNaN** [comment]
THanks to you both will try that ASAP
Sorry I miss the part saying full xcode to be installed.
